const nodemailer = require("nodemailer");

/* ================= ENV SAFETY ================= */
if (!process.env.SYSTEM_EMAIL || !process.env.SYSTEM_EMAIL_APP_PASSWORD) {
  console.error("❌ SYSTEM EMAIL ENV MISSING");
}

/* ================= HTML ESCAPE (ANTI INJECTION) ================= */
function escapeHTML(str = "") {
  return String(str)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

/* ================= EMAIL VALIDATOR ================= */
function validEmail(email) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email || "");
}

/* ================= TRANSPORT (SECURE TLS) ================= */
const transporter = nodemailer.createTransport({
  host: "smtp.gmail.com",
  port: 465,
  secure: true,
  auth: {
    user: process.env.SYSTEM_EMAIL,
    pass: process.env.SYSTEM_EMAIL_APP_PASSWORD
  }
});

/* ================= LOW LEVEL SEND ================= */
async function sendEmail({ to, subject, html }) {
  if (!validEmail(to)) {
    throw new Error("Invalid recipient email");
  }

  return transporter.sendMail({
    from: `"Police CEMS" <${process.env.SYSTEM_EMAIL}>`,
    to,
    subject,
    html
  });
}

/* ================= SAFE SEND ================= */
async function safeSendEmail(options) {
  try {
    await sendEmail(options);
    return { ok: true };
  } catch (err) {
    console.error("Email send error:", err.message);
    return { ok: false, error: err.message };
  }
}

/* ================= EVENT → EMAIL ================= */
function buildEmailForEvent(eventType, data) {
  switch (eventType) {
    /* ========================================= */
    case "EVIDENCE_CREATED":
      return {
        to: data.email,
        subject: `[Police CEMS] Evidence Logged – ${escapeHTML(data.evidenceCode)}`,
        html: `
        <div style="font-family: Arial; background:#0f172a; color:#e5e7eb; padding:24px;">
          <h2 style="color:#60a5fa;">Evidence Successfully Logged</h2>
          <table style="margin-top:16px;">
            <tr><td><b>Evidence Code</b></td><td>${escapeHTML(data.evidenceCode)}</td></tr>
            <tr><td><b>Case Number</b></td><td>${escapeHTML(data.caseNumber)}</td></tr>
            <tr><td><b>Station</b></td><td>${escapeHTML(data.station)}</td></tr>
          </table>
          <p style="margin-top:20px;font-size:12px;color:#9ca3af;">
          Auto generated by Police CEMS
          </p>
        </div>
        `,
        referenceId: data.evidenceId
      };

      case "USER_APPROVED":
  return {
    to: data.email,
    subject: `[Police CEMS] Account Approved`,
    html: `
      <div style="font-family: Arial; background:#020617; color:#e5e7eb; padding:24px;">
        <h2 style="color:#22c55e;">Account Approved</h2>
        <p>Hello ${escapeHTML(data.fullName)},</p>
        <p>Your officer account has been approved by the administrator.</p>
        <table style="margin-top:16px;">
          <tr><td><b>Login ID</b></td><td>${escapeHTML(data.loginId)}</td></tr>
        </table>
        <p style="margin-top:16px;">
          You may now login to Police CEMS.
        </p>
      </div>
    `,
    referenceId: data.userId
  };

  case "USER_BLOCKED":
  return {
    to: data.email,
    subject: `[Police CEMS] Account Blocked`,
    html: `
      <div style="font-family: Arial; background:#020617; color:#e5e7eb; padding:24px;">
        <h2 style="color:#ef4444;">Account Blocked</h2>
        <p>Hello ${escapeHTML(data.fullName)},</p>
        <p>Your account has been blocked by the administrator.</p>
        <p>If you believe this is a mistake, please contact the system administrator.</p>
      </div>
    `,
    referenceId: data.userId
  };

    /* ========================================= */
    case "USER_REGISTERED_NOTIFICATION":
  return {
    to: process.env.SYSTEM_EMAIL, // SEND TO ADMIN
    subject: `[Police CEMS] New Officer Registration – ${escapeHTML(data.loginId)}`,
    html: `
      <div style="font-family: Arial; background:#020617; color:#e5e7eb; padding:24px;">
        <h2 style="color:#facc15;">New Officer Registration Pending Approval</h2>
        <table style="margin-top:16px;">
          <tr><td><b>Name</b></td><td>${escapeHTML(data.fullName)}</td></tr>
          <tr><td><b>Login ID</b></td><td>${escapeHTML(data.loginId)}</td></tr>
          <tr><td><b>Email</b></td><td>${escapeHTML(data.email)}</td></tr>
          <tr><td><b>Role</b></td><td>${escapeHTML(data.role)}</td></tr>
        </table>
        <p style="margin-top:16px;font-size:12px;color:#9ca3af;">
          Action required: Please review and approve this account.
        </p>
      </div>
    `,
    referenceId: data.userId
  };

    /* ========================================= */
    case "EVIDENCE_TRANSFERRED":
      return {
        to: data.email,
        subject: `[Police CEMS] Custody Transfer – ${escapeHTML(data.evidenceCode)}`,
        html: `
        <div style="font-family: Arial; background:#020617; color:#e5e7eb; padding:24px;">
          <h2 style="color:#38bdf8;">Evidence Custody Assigned</h2>
          <table style="margin-top:16px;">
            <tr><td>Evidence</td><td>${escapeHTML(data.evidenceCode)}</td></tr>
            <tr><td>Case</td><td>${escapeHTML(data.caseNumber)}</td></tr>
            <tr><td>Transfer ID</td><td>${escapeHTML(data.transferId)}</td></tr>
            <tr><td>From</td><td>${escapeHTML(data.fromStation)}</td></tr>
            <tr><td>To</td><td>${escapeHTML(data.toStation)}</td></tr>
          </table>
        </div>
        `,
        referenceId: data.transferId
      };

    /* ========================================= */
    case "PASSWORD_RESET_REQUESTED":
      return {
        to: data.email,
        subject: `[Police CEMS] Password Reset Request`,
        html: `
        <div style="font-family: Arial; background:#020617; color:#e5e7eb; padding:24px;">
          <h2 style="color:#38bdf8;">Password Reset Requested</h2>
          <p>Hello ${escapeHTML(data.fullName)},</p>
          <p>Click below to reset your password.</p>
          <a href="${escapeHTML(data.resetLink)}"
             style="display:inline-block;padding:12px 20px;background:#2563eb;color:white;text-decoration:none;border-radius:6px;margin-top:12px;">
             Reset Password
          </a>
          <p style="margin-top:16px;font-size:12px;">
          Link expires in 15 minutes.
          </p>
        </div>
        `,
        referenceId: data.userId
      };

    /* ========================================= */
    case "PASSWORD_CHANGED":
      return {
        to: data.email,
        subject: `[Police CEMS] Password Changed`,
        html: `
        <div style="font-family: Arial; background:#020617; color:#e5e7eb; padding:24px;">
          <h2 style="color:#22c55e;">Password Updated</h2>
          <p>Hello ${escapeHTML(data.fullName)}</p>
          <p>Your password was successfully changed.</p>
          <table style="margin-top:16px;">
            <tr><td>Login ID</td><td>${escapeHTML(data.loginId)}</td></tr>
            <tr><td>Time</td><td>${new Date().toLocaleString()}</td></tr>
          </table>
        </div>
        `,
        referenceId: data.userId
      };
    default:
      throw new Error(`Unknown email event: ${eventType}`);
  }
}

/* ================= LEDGER GUARANTEED ================= */
async function sendEventEmail({ eventType, data, db }) {
  const { to, subject, html, referenceId } =
    buildEmailForEvent(eventType, data);

  const result = await safeSendEmail({ to, subject, html });

  await db.query(`
    INSERT INTO email_ledger
    (event_type, recipient_email, subject, reference_id, delivery_status, error_message, attempted_at)
    VALUES ($1,$2,$3,$4,$5,$6,NOW())
  `, [
    eventType,
    to,
    subject,
    referenceId,
    result.ok ? "SENT" : "FAILED",
    result.ok ? null : result.error
  ]);
  return result;
}

module.exports = { sendEventEmail };
